[build]
command = "npm run build"
watch = ["src"]

[site]
bucket = "dist"
entry-point = "dist/index.html"

[env.production]
compatibility_date = "2023-05-01"
compatibility_flags = []

[env.staging]
compatibility_date = "2023-05-01"
compatibility_flags = []

[build.upload]
main = "dist/index.html"
type = "static"

[build.upload.files]
"dist/**/*" = "dist/**/*"
